# Generated by Django 6.1 on 2026-09-03 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customer_address_customer_city_customer_commune'),
        ('orders', '0004_order_delivery_address_order_delivery_city_and_more'),
        ('organizations', '0008_branch_address_branch_city_branch_commune_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPortalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('SUSPENDED', 'Suspendido')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portal_accounts', to='organizations.company')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='portal_account', to='customers.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portal_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_id', 'user_id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'company'), name='uniq_portal_account_user_company')],
            },
        ),
        migrations.CreateModel(
            name='PortalOrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=100)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portal_order_requests', to='organizations.company')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='portal_request', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portal_order_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'company', 'idempotency_key'), name='uniq_portal_order_request_key')],
            },
        ),
    ]
