from django.urls import path

from catalog import category_management, views

urlpatterns = [
    path(
        "products/",
        views.product_list_view,
        name="catalog-product-list",
    ),
    path(
        "products/<int:product_id>/",
        views.product_detail_view,
        name="catalog-product-detail",
    ),
    path(
        "products/<int:product_id>/variants/",
        views.product_variant_create_view,
        name="catalog-product-variant-create",
    ),
    path(
        "products/<int:product_id>/variants/<int:variant_id>/",
        views.product_variant_detail_view,
        name="catalog-product-variant-detail",
    ),
    path(
        "products/options/",
        views.product_options_view,
        name="catalog-product-options",
    ),
    path(
        "categories/",
        views.category_list_create_view,
        name="catalog-category-list-create",
    ),
    path(
        "categories/manage/",
        category_management.category_management_list_view,
        name="catalog-category-management-list",
    ),
    path(
        "categories/<int:category_id>/",
        category_management.category_management_detail_view,
        name="catalog-category-management-detail",
    ),
    path(
        "brands/",
        views.brand_list_create_view,
        name="catalog-brand-list-create",
    ),
    path(
        "suppliers/",
        views.supplier_list_create_view,
        name="catalog-supplier-list-create",
    ),
    path(
        "suppliers/<int:supplier_id>/",
        views.supplier_detail_view,
        name="catalog-supplier-detail",
    ),
]
