# Generated by Django 6.1 on 2026-09-01 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_seed_inventory_transfers_permission"),
        ("orders", "0002_seed_orders_manage_permission"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderInventoryMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CONFIRMATION", "Confirmacion"),
                            ("CANCELLATION", "Anulacion"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inventory_movement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_stock_link",
                        to="inventory.inventorymovement",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="orders.orderitem",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "order_item__order_id",
                    "order_item_id",
                    "created_at",
                    "id",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order_item", "kind"),
                        name="uniq_order_item_stock_movement_kind",
                    ),
                ],
            },
        ),
    ]
