# Generated by Django 5.2.7 on 2025-10-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('order', 'Venta'), ('product_add', 'Alta de producto'), ('restock', 'Reposición de stock'), ('out_of_stock', 'Producto sin stock'), ('message', 'Mensaje a cliente')], max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
