# Generated by Django 5.2.7 on 2026-06-18 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_product_category'),
        ('core', '0005_alter_customer_options_alter_message_options_and_more'),
    ]

    operations = [
    ]
