# Generated by Django 5.2.7 on 2026-06-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_message_options_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='order_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
