# Generated by Django 6.1 on 2026-08-17 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INVITED', 'Invitado'), ('ACTIVE', 'Activo'), ('SUSPENDED', 'Suspendido'), ('LEFT', 'Desvinculado')], default='INVITED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='organizations.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_id', 'user_id'],
            },
        ),
        migrations.CreateModel(
            name='MembershipBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership_branches', to='organizations.branch')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_memberships', to='organizations.companymembership')),
            ],
            options={
                'ordering': ['membership_id', 'branch_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='companymembership',
            constraint=models.UniqueConstraint(fields=('user', 'company'), name='uniq_membership_user_company'),
        ),
        migrations.AddConstraint(
            model_name='membershipbranch',
            constraint=models.UniqueConstraint(fields=('membership', 'branch'), name='uniq_membership_branch'),
        ),
    ]
