# Generated by Django 6.1 on 2026-08-17 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_companymembership_membershipbranch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('scope_behavior', models.CharField(choices=[('COMPANY_ONLY', 'Solo empresa'), ('TENANT_GLOBAL', 'Global de empresa'), ('BRANCH_SCOPED', 'Por sucursal')], max_length=20)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CompanyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('name_normalized', models.CharField(editable=False, max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='organizations.company')),
            ],
            options={
                'ordering': ['company_id', 'name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'name_normalized'), name='uniq_role_company_name_normalized')],
            },
        ),
    ]
