# Generated by Django 6.1 on 2026-08-17 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_permission_companyrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_links', to='organizations.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permission_links', to='organizations.companyrole')),
            ],
            options={
                'ordering': ['role_id', 'permission_id'],
                'constraints': [models.UniqueConstraint(fields=('role', 'permission'), name='uniq_company_role_permission')],
            },
        ),
    ]
