# Generated by Django 6.1 on 2026-08-17 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_companyrolepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='organizations.branch')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='organizations.companymembership')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='organizations.companyrole')),
            ],
            options={
                'ordering': ['membership_id', 'role_id', 'branch_id'],
                'constraints': [models.UniqueConstraint(fields=('membership', 'role', 'branch'), name='uniq_role_assignment_scope')],
            },
        ),
    ]
