# Generated by Django 6.1 on 2026-09-03 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_delivery_address_order_delivery_city_and_more'),
        ('portal', '0001_initial'),
        ('sales', '0002_seed_sales_manage_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoPagoWebhookReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(max_length=100, unique=True)),
                ('request_id', models.CharField(blank=True, default='', max_length=100)),
                ('data_id', models.CharField(max_length=100)),
                ('payload_hash', models.CharField(max_length=64)),
                ('result', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MercadoPagoCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATING', 'Creando preferencia'), ('READY', 'Listo para pagar'), ('PENDING', 'Pago pendiente'), ('APPROVED', 'Pago aprobado'), ('REJECTED', 'Pago rechazado'), ('CANCELLED', 'Pago cancelado'), ('REFUNDED', 'Pago devuelto'), ('UNCERTAIN', 'Resultado incierto')], default='CREATING', max_length=20)),
                ('external_reference', models.CharField(max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=28)),
                ('currency', models.CharField(default='CLP', max_length=3)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('request_hash', models.CharField(max_length=64)),
                ('preference_id', models.CharField(blank=True, default='', max_length=120)),
                ('init_point', models.URLField(blank=True, default='', max_length=1000)),
                ('sandbox_init_point', models.URLField(blank=True, default='', max_length=1000)),
                ('provider_status', models.CharField(blank=True, default='', max_length=40)),
                ('provider_status_detail', models.CharField(blank=True, default='', max_length=120)),
                ('last_payment_id', models.CharField(blank=True, default='', max_length=80)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mercado_pago_checkout', to='orders.order')),
                ('portal_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mercado_pago_checkouts', to='portal.customerportalaccount')),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mercado_pago_checkout', to='sales.sale')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MercadoPagoRemotePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_payment_id', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(max_length=40)),
                ('status_detail', models.CharField(blank=True, default='', max_length=120)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=28)),
                ('currency_id', models.CharField(max_length=3)),
                ('live_mode', models.BooleanField(default=False)),
                ('payload_hash', models.CharField(max_length=64)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remote_payments', to='external_payments.mercadopagocheckout')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MercadoPagoEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PREFERENCE_REQUESTED', 'Preferencia solicitada'), ('PREFERENCE_READY', 'Preferencia creada'), ('PREFERENCE_UNCERTAIN', 'Preferencia incierta'), ('PREFERENCE_RESOLVED', 'Preferencia resuelta'), ('PAYMENT_REFRESHED', 'Pago consultado'), ('WEBHOOK_RECEIVED', 'Webhook recibido'), ('PAYMENT_APPROVED', 'Pago aprobado'), ('PAYMENT_REJECTED', 'Pago rechazado'), ('PAYMENT_PENDING', 'Pago pendiente'), ('PAYMENT_MISMATCH', 'Pago inconsistente'), ('INTERNAL_PAYMENT_RECORDED', 'Pago interno registrado')], max_length=40)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='external_payments.mercadopagocheckout')),
                ('provider_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='external_payments.mercadopagoremotepayment')),
            ],
            options={
                'ordering': ['checkout_id', 'created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='mercadopagocheckout',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='mp_checkout_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='mercadopagocheckout',
            constraint=models.UniqueConstraint(fields=('portal_account', 'idempotency_key'), name='uniq_mp_checkout_account_key'),
        ),
    ]
