# Generated by Django 6.1 on 2026-09-03 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('external_payments', '0001_initial'),
        ('orders', '0004_order_delivery_address_order_delivery_city_and_more'),
        ('organizations', '0008_branch_address_branch_city_branch_commune_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ORDER_CONFIRMED', 'Pedido confirmado'), ('ORDER_PREPARED', 'Pedido preparado'), ('ORDER_DELIVERED', 'Pedido entregado'), ('ORDER_CANCELLED', 'Pedido cancelado'), ('PAYMENT_APPROVED', 'Pago aprobado'), ('PAYMENT_PENDING', 'Pago pendiente'), ('PAYMENT_REJECTED', 'Pago rechazado'), ('PAYMENT_CANCELLED', 'Pago cancelado'), ('PAYMENT_REFUNDED', 'Pago devuelto')], max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENDING', 'Enviando'), ('RETRY', 'Reintento'), ('SENT', 'Enviado'), ('FAILED', 'Fallido'), ('UNCERTAIN', 'Resultado incierto')], default='PENDING', max_length=20)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sender_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('template_name', models.CharField(max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(max_length=180)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sending_started_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=80)),
                ('last_error_message', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactional_notifications', to='external_payments.mercadopagocheckout')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactional_notifications', to='organizations.company')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactional_notifications', to='orders.order')),
            ],
            options={
                'ordering': ['company_id', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionalNotificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('outcome', models.CharField(choices=[('SENT', 'Enviado'), ('RETRY', 'Reintento'), ('FAILED', 'Fallido'), ('UNCERTAIN', 'Incierto')], max_length=20)),
                ('error_code', models.CharField(blank=True, default='', max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_log', to='transactional_notifications.transactionalnotification')),
            ],
            options={
                'ordering': ['notification_id', 'attempt_number', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='transactionalnotification',
            index=models.Index(fields=['status', 'next_attempt_at', 'created_at'], name='tx_notif_pending_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionalnotification',
            index=models.Index(fields=['company', '-created_at'], name='tx_notif_company_idx'),
        ),
        migrations.AddConstraint(
            model_name='transactionalnotification',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uniq_tx_notification_company_key'),
        ),
        migrations.AddConstraint(
            model_name='transactionalnotificationattempt',
            constraint=models.UniqueConstraint(fields=('notification', 'attempt_number'), name='uniq_tx_notification_attempt_number'),
        ),
    ]
