# Generated by Django 6.1 on 2026-09-03 18:08

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_seed_catalog_suppliers_manage_permission'),
        ('customers', '0001_initial'),
        ('organizations', '0007_seed_customers_manage_permission'),
        ('sales', '0002_seed_sales_manage_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicTaxDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.PositiveSmallIntegerField(choices=[(33, 'Factura electronica'), (34, 'Factura no afecta o exenta'), (56, 'Nota de debito electronica'), (61, 'Nota de credito electronica')])),
                ('state', models.CharField(choices=[('DRAFT', 'Borrador'), ('READY', 'Listo'), ('FOLIO_RESERVED', 'Folio reservado'), ('SIGNED', 'Firmado'), ('SUBMITTED', 'Enviado'), ('PROCESSING', 'Procesando'), ('ACCEPTED', 'Aceptado'), ('ACCEPTED_WITH_REPAIR', 'Aceptado con reparo'), ('REJECTED', 'Rechazado'), ('SEND_UNCERTAIN', 'Envio incierto'), ('VOIDED_PRE_SUBMISSION', 'Folio anulado antes de envio'), ('CANCELLED_BY_REFERENCE', 'Anulado por referencia'), ('DISCARDED', 'Descartado')], default='DRAFT', max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active_base', models.BooleanField(default=False)),
                ('issuer_rut', models.CharField(max_length=20)),
                ('issuer_legal_name', models.CharField(max_length=150)),
                ('issuer_business_activity', models.CharField(max_length=150)),
                ('issuer_address', models.CharField(max_length=200)),
                ('issuer_commune', models.CharField(max_length=100)),
                ('issuer_city', models.CharField(blank=True, default='', max_length=100)),
                ('issuer_tax_email', models.EmailField(blank=True, default='', max_length=254)),
                ('receiver_rut', models.CharField(max_length=20)),
                ('receiver_legal_name', models.CharField(max_length=150)),
                ('receiver_business_activity', models.CharField(max_length=150)),
                ('receiver_address', models.CharField(max_length=200)),
                ('receiver_commune', models.CharField(max_length=100)),
                ('receiver_city', models.CharField(blank=True, default='', max_length=100)),
                ('receiver_tax_email', models.EmailField(blank=True, default='', max_length=254)),
                ('net_amount', models.BigIntegerField(default=0)),
                ('exempt_amount', models.BigIntegerField(default=0)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5)),
                ('vat_amount', models.BigIntegerField(default=0)),
                ('total_amount', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='CLP', max_length=3)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('folio', models.PositiveBigIntegerField(blank=True, null=True)),
                ('provider_track_id', models.CharField(blank=True, default='', max_length=120)),
                ('provider_status_code', models.CharField(blank=True, default='', max_length=80)),
                ('provider_status_message', models.CharField(blank=True, default='', max_length=500)),
                ('provider_last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot_hash', models.CharField(max_length=64)),
                ('xml_hash', models.CharField(blank=True, default='', max_length=64)),
                ('creation_idempotency_key', models.CharField(max_length=100)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discarded_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_tax_documents', to='organizations.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_tax_documents', to='organizations.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_electronic_tax_documents', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_tax_documents', to='sales.sale')),
            ],
            options={
                'ordering': ['company_id', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ElectronicTaxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('DRAFT_CREATED', 'Borrador creado'), ('VALIDATED', 'Validado'), ('DISCARDED', 'Descartado'), ('VERSION_CONFLICT', 'Conflicto de version'), ('FOLIO_RESERVED', 'Folio reservado'), ('FOLIO_CONSUMED', 'Folio consumido'), ('FOLIO_VOID_REQUESTED', 'Anulacion tecnica solicitada'), ('SIGNED', 'Firmado'), ('SUBMIT_REQUESTED', 'Envio solicitado'), ('SUBMITTED', 'Enviado'), ('SEND_UNCERTAIN', 'Envio incierto'), ('STATUS_REFRESHED', 'Estado actualizado'), ('ACCEPTED', 'Aceptado'), ('ACCEPTED_WITH_REPAIR', 'Aceptado con reparo'), ('REJECTED', 'Rechazado'), ('CANCELLED_BY_REFERENCE', 'Anulado por referencia'), ('ACCESS_DENIED', 'Acceso denegado'), ('CROSS_TENANT_BLOCKED', 'Acceso cruzado bloqueado'), ('SECRET_OPERATION', 'Operacion sensible'), ('CREDIT_NOTE_CREATED', 'Nota de credito creada'), ('DEBIT_NOTE_CREATED', 'Nota de debito creada')], max_length=40)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('normalized_code', models.CharField(blank=True, default='', max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_tax_events', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_tax_events', to='organizations.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_tax_events', to='organizations.company')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='electronic_tax.electronictaxdocument')),
            ],
            options={
                'ordering': ['document_id', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FolioAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.PositiveSmallIntegerField()),
                ('start_folio', models.PositiveBigIntegerField()),
                ('end_folio', models.PositiveBigIntegerField()),
                ('next_folio', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('EXHAUSTED', 'Agotado'), ('DISABLED', 'Deshabilitado')], default='ACTIVE', max_length=20)),
                ('source_label', models.CharField(blank=True, default='', max_length=120)),
                ('caf_hash', models.CharField(blank=True, default='', max_length=64)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folio_authorizations', to='organizations.company')),
            ],
            options={
                'ordering': ['company_id', 'type_code', 'start_folio'],
            },
        ),
        migrations.AddField(
            model_name='electronictaxdocument',
            name='folio_authorization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='electronic_tax.folioauthorization'),
        ),
        migrations.CreateModel(
            name='FolioReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.PositiveSmallIntegerField()),
                ('folio', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('RESERVED', 'Reservado'), ('CONSUMED', 'Consumido'), ('VOIDED', 'Anulado')], default='RESERVED', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('authorization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='electronic_tax.folioauthorization')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folio_reservations', to='organizations.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folio_reservations', to='organizations.company')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='folio_reservation', to='electronic_tax.electronictaxdocument')),
            ],
            options={
                'ordering': ['company_id', 'type_code', 'folio'],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=60)),
                ('key', models.CharField(max_length=100)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField(default=200)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_tax_idempotency_records', to='organizations.company')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='idempotency_records', to='electronic_tax.electronictaxdocument')),
            ],
            options={
                'ordering': ['company_id', 'operation', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxCompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20)),
                ('legal_name', models.CharField(max_length=150)),
                ('business_activity', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=200)),
                ('commune', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('tax_email', models.EmailField(blank=True, default='', max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_tax_profile', to='organizations.company')),
            ],
            options={
                'ordering': ['company_id'],
            },
        ),
        migrations.CreateModel(
            name='TaxCustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20)),
                ('legal_name', models.CharField(max_length=150)),
                ('business_activity', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=200)),
                ('commune', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('tax_email', models.EmailField(blank=True, default='', max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_tax_profile', to='customers.customer')),
            ],
            options={
                'ordering': ['customer_id'],
            },
        ),
        migrations.CreateModel(
            name='TaxProductProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_category', models.CharField(choices=[('AFFECTED', 'Afecto'), ('EXEMPT', 'Exento/no gravado')], default='AFFECTED', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_tax_profile', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['variant_id'],
            },
        ),
        migrations.CreateModel(
            name='ElectronicTaxLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('sku', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount_amount', models.BigIntegerField(default=0)),
                ('tax_category', models.CharField(choices=[('AFFECTED', 'Afecto'), ('EXEMPT', 'Exento/no gravado')], max_length=20)),
                ('net_amount', models.BigIntegerField(default=0)),
                ('exempt_amount', models.BigIntegerField(default=0)),
                ('vat_amount', models.BigIntegerField(default=0)),
                ('total_amount', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='electronic_tax.electronictaxdocument')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='electronic_tax_lines', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['document_id', 'line_number'],
                'constraints': [models.UniqueConstraint(fields=('document', 'line_number'), name='uniq_dte_line_number'), models.CheckConstraint(condition=models.Q(('line_number__gt', 0)), name='dte_line_number_positive'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='dte_line_quantity_positive'), models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='dte_line_discount_not_negative')],
            },
        ),
        migrations.CreateModel(
            name='ElectronicTaxReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('CANCEL_DOCUMENT', 'Anular documento'), ('CORRECT_TEXT', 'Corregir texto'), ('CANCEL_DEBIT_NOTE', 'Anular nota de debito'), ('CANCEL_CREDIT_NOTE', 'Anular nota de credito'), ('CORRECT_AMOUNTS', 'Corregir montos')], max_length=30)),
                ('reference_code', models.PositiveSmallIntegerField(default=1)),
                ('reference_date', models.DateField()),
                ('referenced_type_code', models.PositiveSmallIntegerField()),
                ('referenced_folio', models.PositiveBigIntegerField()),
                ('description', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='references', to='electronic_tax.electronictaxdocument')),
                ('referenced_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referenced_by', to='electronic_tax.electronictaxdocument')),
            ],
            options={
                'ordering': ['document_id', 'id'],
                'constraints': [models.UniqueConstraint(fields=('document', 'referenced_document', 'reason'), name='uniq_dte_reference_reason')],
            },
        ),
        migrations.AddConstraint(
            model_name='folioauthorization',
            constraint=models.UniqueConstraint(fields=('company', 'type_code', 'start_folio', 'end_folio'), name='uniq_folio_authorization_range'),
        ),
        migrations.AddConstraint(
            model_name='folioauthorization',
            constraint=models.CheckConstraint(condition=models.Q(('start_folio__gt', 0)), name='folio_authorization_start_positive'),
        ),
        migrations.AddConstraint(
            model_name='folioauthorization',
            constraint=models.CheckConstraint(condition=models.Q(('end_folio__gte', models.F('start_folio'))), name='folio_authorization_end_not_before_start'),
        ),
        migrations.AddConstraint(
            model_name='folioauthorization',
            constraint=models.CheckConstraint(condition=models.Q(('next_folio__gte', models.F('start_folio'))), name='folio_authorization_next_not_before_start'),
        ),
        migrations.AddConstraint(
            model_name='electronictaxdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('folio__isnull', False)), fields=('company', 'type_code', 'folio'), name='uniq_dte_company_type_folio'),
        ),
        migrations.AddConstraint(
            model_name='electronictaxdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active_base', True)), fields=('company', 'sale'), name='uniq_dte_active_base_per_sale'),
        ),
        migrations.AddConstraint(
            model_name='electronictaxdocument',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='dte_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='electronictaxdocument',
            constraint=models.CheckConstraint(condition=models.Q(('net_amount__gte', 0)), name='dte_net_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='electronictaxdocument',
            constraint=models.CheckConstraint(condition=models.Q(('exempt_amount__gte', 0)), name='dte_exempt_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='electronictaxdocument',
            constraint=models.CheckConstraint(condition=models.Q(('vat_amount__gte', 0)), name='dte_vat_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='electronictaxdocument',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='dte_total_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='folioreservation',
            constraint=models.UniqueConstraint(fields=('company', 'type_code', 'folio'), name='uniq_folio_reservation_number'),
        ),
        migrations.AddConstraint(
            model_name='idempotencyrecord',
            constraint=models.UniqueConstraint(fields=('company', 'operation', 'key'), name='uniq_dte_idempotency_scope'),
        ),
    ]
