# Generated by Django 6.1 on 2026-09-03 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_tax', '0003_sii_adapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcompanyprofile',
            name='sii_regional_office',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='electronictaxartifact',
            name='kind',
            field=models.CharField(choices=[('SIGNED_ENVELOPE', 'EnvioDTE firmado'), ('RIDE_PDF', 'Representacion impresa PDF'), ('RECEIVER_ENVELOPE', 'EnvioDTE para receptor'), ('RECEIVER_RESPONSE', 'Respuesta XML del receptor')], max_length=32),
        ),
        migrations.AlterField(
            model_name='electronictaxevent',
            name='event_type',
            field=models.CharField(choices=[('DRAFT_CREATED', 'Borrador creado'), ('VALIDATED', 'Validado'), ('DISCARDED', 'Descartado'), ('VERSION_CONFLICT', 'Conflicto de version'), ('FOLIO_RESERVED', 'Folio reservado'), ('FOLIO_CONSUMED', 'Folio consumido'), ('FOLIO_VOID_REQUESTED', 'Anulacion tecnica solicitada'), ('SIGNED', 'Firmado'), ('SUBMIT_REQUESTED', 'Envio solicitado'), ('SUBMITTED', 'Enviado'), ('SEND_UNCERTAIN', 'Envio incierto'), ('STATUS_REFRESHED', 'Estado actualizado'), ('ACCEPTED', 'Aceptado'), ('ACCEPTED_WITH_REPAIR', 'Aceptado con reparo'), ('REJECTED', 'Rechazado'), ('CANCELLED_BY_REFERENCE', 'Anulado por referencia'), ('ACCESS_DENIED', 'Acceso denegado'), ('CROSS_TENANT_BLOCKED', 'Acceso cruzado bloqueado'), ('SECRET_OPERATION', 'Operacion sensible'), ('CREDIT_NOTE_CREATED', 'Nota de credito creada'), ('DEBIT_NOTE_CREATED', 'Nota de debito creada'), ('RIDE_GENERATED', 'RIDE generado'), ('RECEIVER_EXCHANGE_SENT', 'DTE enviado al receptor'), ('RECEIVER_EXCHANGE_UNCERTAIN', 'Envio al receptor incierto'), ('RECEIVER_RESPONSE_RECEIVED', 'Respuesta del receptor recibida')], max_length=40),
        ),
        migrations.CreateModel(
            name='ElectronicTaxExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_state', models.CharField(choices=[('NONE', 'Sin envio'), ('PENDING', 'Preparando envio'), ('SENT', 'Enviado'), ('SEND_UNCERTAIN', 'Envio incierto')], default='NONE', max_length=24)),
                ('recipient_email', models.EmailField(blank=True, default='', max_length=254)),
                ('envelope_hash', models.CharField(blank=True, default='', max_length=64)),
                ('ride_hash', models.CharField(blank=True, default='', max_length=64)),
                ('send_attempts', models.PositiveIntegerField(default=0)),
                ('last_send_error', models.CharField(blank=True, default='', max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('receiver_response_state', models.CharField(choices=[('NONE', 'Sin respuesta'), ('RECEIVED', 'Respuesta recibida'), ('ACCEPTED', 'Aceptado'), ('ACCEPTED_WITH_DISCREPANCY', 'Aceptado con discrepancia'), ('REJECTED', 'Rechazado')], default='NONE', max_length=32)),
                ('receiver_response_code', models.CharField(blank=True, default='', max_length=40)),
                ('receiver_response_message', models.CharField(blank=True, default='', max_length=500)),
                ('receiver_response_hash', models.CharField(blank=True, default='', max_length=64)),
                ('receiver_response_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='exchange', to='electronic_tax.electronictaxdocument')),
            ],
        ),
    ]
