# Generated by Django 6.1 on 2026-09-03 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_tax', '0004_taxcompanyprofile_sii_regional_office_and_more'),
        ('organizations', '0007_seed_customers_manage_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicTaxOperationalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('INFO', 'Informacion'), ('WARNING', 'Advertencia'), ('CRITICAL', 'Critico')], max_length=16)),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('RESOLVED', 'Resuelta')], default='OPEN', max_length=16)),
                ('dedupe_key', models.CharField(max_length=160)),
                ('resource_kind', models.CharField(blank=True, default='', max_length=40)),
                ('resource_id', models.CharField(blank=True, default='', max_length=64)),
                ('message', models.CharField(max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_tax_operational_alerts', to='organizations.company')),
            ],
            options={
                'ordering': ['company_id', '-severity', 'code', 'id'],
                'constraints': [models.UniqueConstraint(fields=('company', 'dedupe_key'), name='uniq_dte_operational_alert_dedupe')],
            },
        ),
        migrations.CreateModel(
            name='ElectronicTaxStatusCheckTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'Ejecutando'), ('SUCCEEDED', 'Completada'), ('FAILED', 'Fallida'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=16)),
                ('reason', models.CharField(max_length=80)),
                ('due_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=8)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_tax_status_check_tasks', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_tax_status_check_tasks', to='organizations.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_tax_status_check_tasks', to='organizations.company')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_check_tasks', to='electronic_tax.electronictaxdocument')),
            ],
            options={
                'ordering': ['due_at', 'id'],
                'indexes': [models.Index(fields=['state', 'due_at'], name='dte_status_task_due_idx'), models.Index(fields=['company', 'state'], name='dte_status_task_cmp_idx')],
            },
        ),
    ]
