# Generated by Django 6.1 on 2026-08-23 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_seed_catalog_suppliers_manage_permission'),
        ('organizations', '0006_seed_warehouses_manage_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stocks', to='catalog.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stocks', to='organizations.warehouse')),
            ],
            options={
                'ordering': ['warehouse_id', 'variant_id'],
                'constraints': [models.UniqueConstraint(fields=('warehouse', 'variant'), name='uniq_inventory_stock_warehouse_variant')],
            },
        ),
    ]
