# Generated by Django 6.1 on 2026-08-26 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_seed_catalog_suppliers_manage_permission'),
        ('inventory', '0004_seed_inventory_movements_permission'),
        ('organizations', '0006_seed_warehouses_manage_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='COMPLETED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transfers', to='organizations.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_inventory_transfers', to=settings.AUTH_USER_MODEL)),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_inventory_transfers', to='organizations.warehouse')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_inventory_transfers', to='organizations.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorytransfer')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transfer_items', to='catalog.productvariant')),
            ],
        ),
    ]
