# Generated by Django 6.1 on 2026-09-22 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_order_sale_scope_and_snapshots(apps, schema_editor):
    Sale = apps.get_model("sales", "Sale")
    SaleItem = apps.get_model("sales", "SaleItem")
    OrderItem = apps.get_model("orders", "OrderItem")

    for sale in Sale.objects.filter(origin="ORDER").select_related("order"):
        order = sale.order
        if order is None:
            continue

        Sale.objects.filter(pk=sale.pk).update(
            customer_id=order.customer_id,
            warehouse_id=order.warehouse_id,
        )
        order_items = (
            OrderItem.objects.filter(order_id=order.pk)
            .select_related("variant__product")
        )
        for order_item in order_items:
            SaleItem.objects.get_or_create(
                sale_id=sale.pk,
                variant_id=order_item.variant_id,
                defaults={
                    "sku_snapshot": order_item.variant.sku,
                    "product_name_snapshot": order_item.variant.product.name,
                    "quantity": order_item.quantity,
                    "unit_price": order_item.unit_price,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_seed_administration_permission'),
        ('catalog', '0009_category_status'),
        ('customers', '0002_customer_address_customer_city_customer_commune'),
        ('inventory', '0006_seed_inventory_transfers_permission'),
        ('orders', '0004_order_delivery_address_order_delivery_city_and_more'),
        ('organizations', '0008_branch_address_branch_city_branch_commune_and_more'),
        ('sales', '0002_seed_sales_manage_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SALE', 'Salida por venta'), ('REVERSAL', 'Reposicion por anulacion')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sale_item_id', 'kind', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_snapshot', models.CharField(max_length=100)),
                ('product_name_snapshot', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sale_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SaleReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=28)),
                ('reference', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sale_id'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_payments', to='administration.paymentmethod'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='origin',
            field=models.CharField(choices=[('ORDER', 'Pedido'), ('POS', 'Venta directa')], default='ORDER', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='organizations.warehouse'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['company', 'origin', '-created_at'], name='sale_co_origin_created_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['company', 'branch', '-number'], name='sale_co_branch_number_idx'),
        ),
        migrations.AddField(
            model_name='saleinventorymovement',
            name='inventory_movement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale_stock_link', to='inventory.inventorymovement'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='saleinventorymovement',
            name='sale_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='sales.saleitem'),
        ),
        migrations.AddField(
            model_name='salereversal',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_reversals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salereversal',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='sales.sale'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.UniqueConstraint(fields=('sale', 'variant'), name='uniq_sale_item_variant'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sale_item_quantity_greater_than_zero'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='sale_item_unit_price_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='saleinventorymovement',
            constraint=models.UniqueConstraint(fields=('sale_item', 'kind'), name='uniq_sale_item_stock_movement_kind'),
        ),
        migrations.AddConstraint(
            model_name='salereversal',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='sale_reversal_amount_greater_than_zero'),
        ),
        migrations.RunPython(
            backfill_order_sale_scope_and_snapshots,
            migrations.RunPython.noop,
        ),
    ]
