# Generated by Django 6.1 on 2026-09-03 21:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0008_branch_address_branch_city_branch_commune_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5)),
                ('currency', models.CharField(default='CLP', max_length=3)),
                ('timezone', models.CharField(default='America/Santiago', max_length=80)),
                ('payment_provider', models.CharField(default='MERCADO_PAGO', max_length=60)),
                ('payment_sandbox_enabled', models.BooleanField(default=True)),
                ('notification_sender_email', models.EmailField(blank=True, default='', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='general_settings', to='organizations.company')),
            ],
            options={
                'ordering': ['company_id'],
            },
        ),
        migrations.CreateModel(
            name='AdministrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=60)),
                ('resource_type', models.CharField(max_length=60)),
                ('resource_id', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administration_events', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administration_events', to='organizations.company')),
            ],
            options={
                'ordering': ['company_id', '-created_at', '-id'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='admin_event_company_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('display_name', models.CharField(max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_status_configurations', to='organizations.company')),
            ],
            options={
                'ordering': ['company_id', 'sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='uniq_admin_order_status_company_code')],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('CASH', 'Efectivo'), ('TRANSFER', 'Transferencia'), ('ONLINE', 'Pago en linea'), ('OTHER', 'Otro')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_methods', to='organizations.company')),
            ],
            options={
                'ordering': ['company_id', 'sort_order', 'name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='uniq_admin_payment_method_company_code')],
            },
        ),
    ]
